import Head from "next/head";
import Link from "next/link";
import Navbar from "./Navbar";

interface Props {
  children: React.ReactNode;
}

export default function Container(props: Props) {
  const { children } = props;
  return (
    <div>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      <main className="flex flex-col justify-center py-2 px-8">{children}</main>
    </div>
  );
}
