import Head from "next/head";
import Link from "next/link";

interface Props {
  children: React.ReactNode;
}

export default function Container(props: Props) {
  const { children } = props;
  return (
    <div>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <nav className="sticky top-0 bg-white py-2 px-8 shadow">
        <div className="mx-auto flex w-full max-w-4xl">
          <div className="flex w-full items-center justify-between">
            <div className="items-center space-x-4">
              <Link href="/home">Home</Link>
              <Link href="/home">About</Link>
            </div>
            <button className="rounded border border-blue-500 bg-blue-500 py-2 px-6 text-sm text-white hover:bg-white hover:text-blue-500">
              Sign in
            </button>
          </div>
        </div>
      </nav>
      <main className="flex flex-col justify-center py-2 px-8">{children}</main>
    </div>
  );
}
